[Link To Tutorial](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)

In [1]:
## import necessary modules
from __future__ import print_function
import torch

In [2]:
## versions
print(f"PyTorch: {torch.__version__}")

PyTorch: 1.7.0


## Tensors

* Tensors are similar to Numpy's ndarray, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [5]:
## a 6x4 matrix
mat = torch.empty(6, 4)

mat

tensor([[-3.2810e-01,  3.0754e-41,  0.0000e+00,  0.0000e+00],
        [-3.3760e-01,  3.0754e-41, -3.3760e-01,  3.0754e-41],
        [-3.3760e-01,  3.0754e-41,  0.0000e+00,  0.0000e+00],
        [ 8.5924e+30,  4.5898e-41,  8.6132e+30,  4.5898e-41],
        [ 9.8670e-28, -6.8178e+35,  8.8779e+30,  4.5898e-41],
        [-3.3760e-01,  3.0754e-41, -3.3760e-01,  3.0754e-41]])

In [6]:
## a randomly initialized matrix
rand_mat = torch.rand(6, 4)

rand_mat

tensor([[0.2090, 0.7392, 0.5284, 0.9114],
        [0.6992, 0.0203, 0.4356, 0.8935],
        [0.8298, 0.3358, 0.3435, 0.0930],
        [0.3344, 0.6736, 0.9154, 0.8368],
        [0.2075, 0.3623, 0.6710, 0.4790],
        [0.4907, 0.3214, 0.5296, 0.0214]])

In [13]:
## matrix of zero, dtype long
zero_mat = torch.zeros((6, 4), dtype=torch.long)

zero_mat

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [14]:
## construct a tensor directly from data
data_tensor = torch.tensor([1, 2, 3, 4, 5])

data_tensor

tensor([1, 2, 3, 4, 5])

In [16]:
## get the size
data_tensor.size()

torch.Size([5])

## Operations

1) Addition

In [28]:
x = torch.rand(5, 4)
y = torch.rand(5, 4)

In [29]:
x, y

(tensor([[0.0066, 0.7633, 0.3157, 0.4389],
         [0.4060, 0.7329, 0.6234, 0.6100],
         [0.6463, 0.1608, 0.6221, 0.2454],
         [0.9475, 0.0703, 0.8764, 0.1652],
         [0.0137, 0.2885, 0.2287, 0.9956]]),
 tensor([[0.2131, 0.1403, 0.0149, 0.4019],
         [0.5763, 0.0392, 0.9531, 0.8557],
         [0.4949, 0.8877, 0.1309, 0.5898],
         [0.8449, 0.0267, 0.3166, 0.7949],
         [0.8213, 0.7770, 0.2186, 0.2124]]))

In [30]:
## add two tensor
x + y

tensor([[0.2197, 0.9036, 0.3306, 0.8408],
        [0.9823, 0.7721, 1.5765, 1.4657],
        [1.1412, 1.0485, 0.7530, 0.8351],
        [1.7924, 0.0970, 1.1930, 0.9601],
        [0.8351, 1.0655, 0.4473, 1.2080]])

In [31]:
## other way
torch.add(x, y)

tensor([[0.2197, 0.9036, 0.3306, 0.8408],
        [0.9823, 0.7721, 1.5765, 1.4657],
        [1.1412, 1.0485, 0.7530, 0.8351],
        [1.7924, 0.0970, 1.1930, 0.9601],
        [0.8351, 1.0655, 0.4473, 1.2080]])

In [32]:
## add two tensors and store result in third variable

## make tensor where result will be stored
result = torch.empty(5, 4)

torch.add(x, y, out=result)

result

tensor([[0.2197, 0.9036, 0.3306, 0.8408],
        [0.9823, 0.7721, 1.5765, 1.4657],
        [1.1412, 1.0485, 0.7530, 0.8351],
        [1.7924, 0.0970, 1.1930, 0.9601],
        [0.8351, 1.0655, 0.4473, 1.2080]])

In [33]:
## another way
result = x + y

result

tensor([[0.2197, 0.9036, 0.3306, 0.8408],
        [0.9823, 0.7721, 1.5765, 1.4657],
        [1.1412, 1.0485, 0.7530, 0.8351],
        [1.7924, 0.0970, 1.1930, 0.9601],
        [0.8351, 1.0655, 0.4473, 1.2080]])

In [34]:
## in place addition: add x to y
y.add_(x)

y

tensor([[0.2197, 0.9036, 0.3306, 0.8408],
        [0.9823, 0.7721, 1.5765, 1.4657],
        [1.1412, 1.0485, 0.7530, 0.8351],
        [1.7924, 0.0970, 1.1930, 0.9601],
        [0.8351, 1.0655, 0.4473, 1.2080]])

> Note: Any operation that mutates a tensor in-place is post-fixed with an _ . For example: x.copy_(y), x.t_(), will change x.

02) Slicing

In [37]:
## slicing
x[:, 2:4]

tensor([[0.3157, 0.4389],
        [0.6234, 0.6100],
        [0.6221, 0.2454],
        [0.8764, 0.1652],
        [0.2287, 0.9956]])

03) Resize

In [38]:
## torch.view
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)

In [39]:
x

tensor([[-0.0089, -0.5315, -0.6245,  0.5478],
        [-0.2586,  0.5438, -0.8006, -0.2822],
        [ 0.6518, -0.6069, -0.3926, -0.8972],
        [-2.1697,  2.4787,  0.8592,  0.0890]])

In [40]:
y

tensor([-0.0089, -0.5315, -0.6245,  0.5478, -0.2586,  0.5438, -0.8006, -0.2822,
         0.6518, -0.6069, -0.3926, -0.8972, -2.1697,  2.4787,  0.8592,  0.0890])

In [41]:
z

tensor([[-0.0089, -0.5315, -0.6245,  0.5478, -0.2586,  0.5438, -0.8006, -0.2822],
        [ 0.6518, -0.6069, -0.3926, -0.8972, -2.1697,  2.4787,  0.8592,  0.0890]])

04) One element tensor

In [47]:
x = torch.randn(1)

x, x.item()

(tensor([0.6217]), 0.6217015385627747)

05) Converting NumPy Array to Torch Tensor

In [57]:
import numpy as np

a = np.ones(5)
b = torch.from_numpy(a)  ## picks from the same memory location

np.add(a, 1, out=a)

a, b

(array([2., 2., 2., 2., 2.]),
 tensor([2., 2., 2., 2., 2.], dtype=torch.float64))

06) CUDA Tensor

In [58]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU

if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([1.6217], device='cuda:0')
tensor([1.6217], dtype=torch.float64)
